**These days, NFTs are making a splash in the market by providing people with a new option to acquire assets. Between the second and third quarter of 2021, NFT trading increased 700% ($10.7 billion) according to DappRadar.** 

**whether they’ve been used for exchanges or as investments, NFTs have been applied to various fields, including science, technology, and art. With NFTs becoming more popular, RMDS Lab is announcing its next data science competition - Creating a NFT Value Dashboard to Summarize the Past and Predict the Future.**

**Contestants will be challenged with collecting datasets to create a dashboard that assesses trends in the development of NFTs and forecast their future trajectory.**

Evaluation
Impact: What useful business insights are acquired from the proposal? How does this submitted model benefit (or cost) businesses, and what actionable steps are recommended to improve their work?​

Methodology Valdity: Document the methodology, mathematics, and economic principles behind the proposal and provide the references or reasoning for your approach. How is the prediction generated and how are the factors weighted sensible? Are the assumptions and limitations of the methodology clearly outlined with suggestions to improve the proposal? Are the quantitative steps of data ingestion, feature engineering, model architecture, and performance optimization valid? How robust is your model?

Reproducibility: Does the solution use coding best practices with workflows and documentation to reproduce one’s work? Are the data ingress and egress pipelines reproducible? Is there a clear presentation of data science work in the documentation?

Usability: Is the information presented in a way that is actionable? Would a member of the general public understand the model, what it means, and what actions to take?

Ability to Deploy:Is getting access to the data realistic? How long is the computation time? How well is the scalability of the system to accept new data sources? How often does it need to be maintained? Is it    hard to maintain/update? How much manpower, time, resources are needed to be allocated to maintain the functionality?

Fair and Ethical Use of Data: Does the solution consider biases in data? Is the data from open and trusted sources?

Innovation: Will the idea have a big impact? How innovative is the approach, selection and weighting of various factors, or how information is displayed and communicated?

Sample Research Questions

- NFT investors and buyers may want to know:

- What types of NFTs are higher valued than others?
- What types of NFTs have their values going up?​
- What science & tech NFTs are popular?
- What types of science & technology IPs are in demand and enjoy a value uptrend?
- Can we build a financial/ML model to forecast the price of NFTs encrypted by ourselves?
- Which cryptocurrency is trending recently?
- Why could some NFTs be sold at a huge price?
- What types of NFTs are most encrypted by the general public?
- What are the main differences in NFT transactions among some major marketplaces?
- What's the best listing duration for a timed auction?
- What’s the most acceptable price range for our listings to finish a deal?
- How do you predict the future of the NFT transactions?

Feature Name	Feature Description																								
- primary_asset_contracts_address	The asset contracts address that is associated with this collection																								
- primary_asset_contracts_asset_contract_type	The asset contracts type that is associated with this collection. Can be non-fungible or semi-fungible

- primary_asset_contracts_created_date	The created date of the asset contract that is associated with this collection																								
- primary_asset_contracts_name	The contract name of the asset that is associated with this collection																								
- primary_asset_contracts_nft_version	The NFT version of the asset contract that is associated with this collection																								
- primary_asset_contracts_owner	The owner ID of the asset contract that is associated with this collection																								
- primary_asset_contracts_schema_name	The shema version that the asset contract used which is associated with the collection. Can be ERC721, ERC1155 etc	

- primary_asset_contracts_symbol	The symbol of the asset contract that is associated with this collection																								
- primary_asset_contracts_total_supply	The total number of supply in the asset contract that is associated with this collection																								
- primary_asset_contracts_description	The description of the asset contract that is associated with this collection																								
- primary_asset_contracts_dev_seller_fee_basis_points	The collector's fees that get paid out to them when sales (including re-sales) are made for their collections. One basis point equals to 0.0001																								
- primary_asset_contracts_seller_fee_basis_points	The seller fees in the sales. One basis point equals to 0.0001																								
- primary_asset_contracts_payout_address	The payout address for the collection's royalties

stats_one_day_volume	The one day trade volume in this collection. The timestamp of the data collected is on stats_time																								
stats_one_day_change	The one day trade volume change in this collection. The timestamp of the data collected is on stats_time																								
stats_one_day_sales	The one day number of sales in this collection. The timestamp of the data collected is on stats_time																								
stats_one_day_average_price	The one day average price of the items in this collection. The timestamp of the data collected is on stats_time																								
stats_seven_day_volume	The seven days trade volume in this collection. The timestamp of the data collected is on stats_time																								
stats_seven_day_change	The seven days trade volume change in this collection. The timestamp of the data collected is on stats_time																								
stats_seven_day_sales	The seven days number of sales in this collection. The timestamp of the data collected is on stats_time																								
stats_seven_day_average_price	The seven days average price of the items in this collection. The timestamp of the data collected is on stats_time

- stats_thirty_day_volume	The thirty days trade volume in this collection. The timestamp of the data collected is on stats_time	

- stats_thirty_day_change	The thirty days trade volume change in this collection. The timestamp of the data collected is on stats_time	

- stats_thirty_day_sales	The thirty days number of sales in this collection. The timestamp of the data collected is on stats_time

- stats_thirty_day_average_price	The thirty days average price of the items in this collection. The timestamp of the data collected is on stats_time	 

- stats_total_volume	The total trade volume in this collection. The timestamp of the data collected is on stats_time																								
- stats_total_sales	The total number of sales in this collection. The timestamp of the data collected is on stats_time																								
- stats_total_supply	The total number of supply in this collection. The timestamp of the data collected is on stats_time																								
- stats_count	The total number of items in this collection.  The timestamp of the data collected is on stats_time																								
- stats_num_owners	The total number of owners for all the items in the collection. The timestamp of the data collected is on stats_time	

- stats_average_price	The average price of the items in this collection. The timestamp of the data collected is on stats_time																								
- stats_market_cap	The market capitalization of the items in this collection. The timestamp of the data collected is on stats_time	

- stats_floor_price	The floor price of the items in this collection. The timestamp of the data collected is on stats_time																								
- stats_time	The timestamp of collection date for the stats data																								
- slug	The collection slug that is used to link to the collection on OpenSea. This value can change by the owner but must be unique across all collection slugs in OpenSea

- created_date	The date that the collection was created by user																								
- description	The description of the collection																								
- display_data_card_display_style	The way that the collection's data displayed as, including contain, cover, padded																								
- safelist_request_status	The collection's approval status within OpenSea. Can be not_requested (brand new collections), requested (collections that requested safelisting on our site), approved (collections that are approved on our site and can be found in search results), and verified (verified collections)																								
- name	The collection name. Typically derived from the first contract imported to the collection but can be changed by the user																								
- telegram_url	A boolean whether the collector provide telegram profile url																								
- twitter_username	A boolean whether the collector provide twitter account name																								
- instagram_username	A boolean whether the collector provide instagram account name																								
- medium_username	A boolean whether the collector provide medium account name																								
- external_url	External link to the original website for the collection																								
- discord_url	The url of the discord, which contains channels serve as the places where community members can discuss particular topic. The number of members could be an important feature of the value of NFT collection

In [1]:
pip install sweetviz

Requirement already satisfied: sweetviz in c:\users\satvik\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: tqdm>=4.43.0 in c:\users\satvik\anaconda3\lib\site-packages (from sweetviz) (4.62.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in c:\users\satvik\anaconda3\lib\site-packages (from sweetviz) (1.3.4)
Requirement already satisfied: importlib-resources>=1.2.0 in c:\users\satvik\anaconda3\lib\site-packages (from sweetviz) (5.6.0)
Requirement already satisfied: numpy>=1.16.0 in c:\users\satvik\anaconda3\lib\site-packages (from sweetviz) (1.20.3)
Requirement already satisfied: matplotlib>=3.1.3 in c:\users\satvik\anaconda3\lib\site-packages (from sweetviz) (3.4.3)
Requirement already satisfied: scipy>=1.3.2 in c:\users\satvik\anaconda3\lib\site-packages (from sweetviz) (1.7.1)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\satvik\anaconda3\lib\site-packages (from sweetviz) (2.11.3)
Requirement already satisfied: zipp>=3.1.0 in c:\users\satvik\anaconda3\lib\site-packages (from importlib-resources>=1.2.0->sweetviz) (3.6.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\satvik\anaconda3\lib\site-packages (from jinja2>=2.11.1->sweetviz) (2.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\satvik\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\satvik\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\satvik\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (8.4.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\satvik\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\satvik\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.0.4)
Requirement already satisfied: six in c:\users\satvik\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=3.1.3->sweetviz) (1.16.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\satvik\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2021.3)
Requirement already satisfied: colorama in c:\users\satvik\anaconda3\lib\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.4)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd
import matplotlib.pyplot as plt

In [17]:
col_df=pd.read_csv('collections.csv')

In [18]:
col_df.info()
col_df.loc[col_df.isna().any(axis=1)]
col_df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1427 entries, 0 to 1426
Data columns (total 46 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   primary_asset_contracts_address                      962 non-null    object
 1   primary_asset_contracts_asset_contract_type          962 non-null    object
 2   primary_asset_contracts_created_date                 962 non-null    object
 3   primary_asset_contracts_name                         961 non-null    object
 4   primary_asset_contracts_nft_version                  870 non-null    object
 5   primary_asset_contracts_owner                        909 non-null    float64
 6   primary_asset_contracts_schema_name                  962 non-null    object
 7   primary_asset_contracts_symbol                       894 non-null    object
 8   primary_asset_contracts_total_supply                 772 non-null    float64
 9   primary_asset_contracts_description                  948 non-null    object
 10  primary_asset_contracts_dev_seller_fee_basis_points  962 non-null    float64
 11  primary_asset_contracts_seller_fee_basis_points      962 non-null    float64
 12  primary_asset_contracts_payout_address               920 non-null    object
 13  stats_one_day_volume                                 1427 non-null   float64
 14  stats_one_day_change                                 1427 non-null   float64
 15  stats_one_day_sales                                  1427 non-null   int64
 16  stats_one_day_average_price                          1427 non-null   float64
 17  stats_seven_day_volume                               1427 non-null   float64
 18  stats_seven_day_change                               1427 non-null   float64
 19  stats_seven_day_sales                                1427 non-null   int64
 20  stats_seven_day_average_price                        1427 non-null   float64
 21  stats_thirty_day_volume                              1427 non-null   float64
 22  stats_thirty_day_change                              1427 non-null   float64
 23  stats_thirty_day_sales                               1427 non-null   int64
 24  stats_thirty_day_average_price                       1427 non-null   float64
 25  stats_total_volume                                   1427 non-null   float64
 26  stats_total_sales                                    1427 non-null   float64
 27  stats_total_supply                                   1427 non-null   int64
 28  stats_count                                          1427 non-null   int64
 29  stats_num_owners                                     1427 non-null   int64
 30  stats_average_price                                  1427 non-null   float64
 31  stats_market_cap                                     1427 non-null   float64
 32  stats_floor_price                                    1370 non-null   float64
 33  slug                                                 1426 non-null   object
 34  stats_time                                           1427 non-null   object
 35  created_date                                         1427 non-null   object
 36  description                                          1396 non-null   object
 37  display_data_card_display_style                      1426 non-null   object
 38  safelist_request_status                              1427 non-null   object
 39  name                                                 1426 non-null   object
 40  telegram_url                                         1427 non-null   int64
 41  twitter_username                                     1427 non-null   int64
 42  instagram_username                                   1427 non-null   int64
 43  discord_url                                          1427 non-null   int64
 44  medium_username                                      1427 non-null   int64
 45  external_url                                         1165 non-null   object
dtypes: float64(18), int64(11), object(17)
memory usage: 513.0+ KB

Index(['primary_asset_contracts_address',
       'primary_asset_contracts_asset_contract_type',
       'primary_asset_contracts_created_date', 'primary_asset_contracts_name',
       'primary_asset_contracts_nft_version', 'primary_asset_contracts_owner',
       'primary_asset_contracts_schema_name', 'primary_asset_contracts_symbol',
       'primary_asset_contracts_total_supply',
       'primary_asset_contracts_description',
       'primary_asset_contracts_dev_seller_fee_basis_points',
       'primary_asset_contracts_seller_fee_basis_points',
       'primary_asset_contracts_payout_address', 'stats_one_day_volume',
       'stats_one_day_change', 'stats_one_day_sales',
       'stats_one_day_average_price', 'stats_seven_day_volume',
       'stats_seven_day_change', 'stats_seven_day_sales',
       'stats_seven_day_average_price', 'stats_thirty_day_volume',
       'stats_thirty_day_change', 'stats_thirty_day_sales',
       'stats_thirty_day_average_price', 'stats_total_volume',
       'stats_total_sales', 'stats_total_supply', 'stats_count',
       'stats_num_owners', 'stats_average_price', 'stats_market_cap',
       'stats_floor_price', 'slug', 'stats_time', 'created_date',
       'description', 'display_data_card_display_style',
       'safelist_request_status', 'name', 'telegram_url', 'twitter_username',
       'instagram_username', 'discord_url', 'medium_username', 'external_url'],
      dtype='object')

In [22]:
col_df['primary_asset_contracts_dev_seller_fee_basis_points'].sort_values(ascending=False)
col_df['primary_asset_contracts_dev_seller_fee_basis_points'].value_counts()
col_df[['primary_asset_contracts_dev_seller_fee_basis_points','primary_asset_contracts_seller_fee_basis_points','primary_asset_contracts_name']]

,primary_asset_contracts_dev_seller_fee_basis_points,primary_asset_contracts_seller_fee_basis_points,primary_asset_contracts_name
0,NaN,NaN,NaN
1,NaN,NaN,NaN
2,NaN,NaN,NaN
3,NaN,NaN,NaN
4,750.0,1000.0,AlphieWhales
...,...,...,...
1422,NaN,NaN,NaN
1423,1000.0,1250.0,HUXLEY Comics
1424,1000.0,1250.0,Unidentified contract
1425,1000.0,1250.0,Squishy Apes
1426,NaN,NaN,NaN

In [29]:
col_df['primary_asset_contracts_nft_version'].value_counts()

3              866
unsupported      3
1                1
Name: primary_asset_contracts_nft_version, dtype: int64

In [30]:
col_df['primary_asset_contracts_address'].value_counts()

0x417737d49a175d62625154262d8569d3890425ae    1
0x8fff2195728aaf62684d49d5039b69cee1f94542    1
0x75e9abc7e69fc46177d2f3538c0b92d89054ec91    1
0x75b7d9fe942fb1c7d10885d5315081a63f89706d    1
0x586e1dfa8ceb7d7c46c2f616a04b0d2e995520a4    1
                                             ..
0x78f190efe7b9198b76207f14d90ba96fb782680e    1
0xa49f31c7c90137e8d76fcf339e242e97b8f417d9    1
0xdf93e81f3231afaea101861ea3f6ca109fb075aa    1
0xa32210529c69cca8cfc58dbfdbf06654288462f5    1
0x26c813804430772665b0d38a3a0520a9c87c10b4    1
Name: primary_asset_contracts_address, Length: 962, dtype: int64

In [7]:
pd.set_option('display.max_columns', None)

In [8]:
primary_contract=['primary_asset_contracts_address',
       'primary_asset_contracts_asset_contract_type',
       'primary_asset_contracts_created_date', 'primary_asset_contracts_name',
       'primary_asset_contracts_nft_version', 'primary_asset_contracts_owner',
       'primary_asset_contracts_schema_name', 'primary_asset_contracts_symbol',
       'primary_asset_contracts_total_supply',
       'primary_asset_contracts_description',
       'primary_asset_contracts_dev_seller_fee_basis_points',
       'primary_asset_contracts_seller_fee_basis_points',
       'primary_asset_contracts_payout_address']

In [9]:
col_df[col_df[primary_contract].isnull().all(axis=1)]

,primary_asset_contracts_address,primary_asset_contracts_asset_contract_type,primary_asset_contracts_created_date,primary_asset_contracts_name,primary_asset_contracts_nft_version,primary_asset_contracts_owner,primary_asset_contracts_schema_name,primary_asset_contracts_symbol,primary_asset_contracts_total_supply,primary_asset_contracts_description,primary_asset_contracts_dev_seller_fee_basis_points,primary_asset_contracts_seller_fee_basis_points,primary_asset_contracts_payout_address,stats_one_day_volume,stats_one_day_change,stats_one_day_sales,stats_one_day_average_price,stats_seven_day_volume,stats_seven_day_change,stats_seven_day_sales,stats_seven_day_average_price,stats_thirty_day_volume,stats_thirty_day_change,stats_thirty_day_sales,stats_thirty_day_average_price,stats_total_volume,stats_total_sales,stats_total_supply,stats_count,stats_num_owners,stats_average_price,stats_market_cap,stats_floor_price,slug,stats_time,created_date,description,display_data_card_display_style,safelist_request_status,name,telegram_url,twitter_username,instagram_username,discord_url,medium_username,external_url
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.050,0.000000,1,0.0500,0.210000,-0.468354,4,0.052500,1.666000,-0.554605,33,0.050485,11.497400,184.0,9970,9970,138,0.062486,523.425000,0.0390,spiritman,"2022-03-06, 09:45:19",2021-08-19T03:59:37.338711,Arri Novrizal[@fujhine](https://www.instagram....,contain,approved,Spirit Man,0,1,1,1,0,http://www.spiritman.io
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.058,-0.479354,2,0.0290,0.543511,-0.192885,24,0.022646,3.651611,-0.977126,144,0.025358,205.010570,4107.0,9655,9655,2167,0.049917,218.649991,0.0159,byteosaurus,"2022-03-06, 09:45:20",2021-03-06T14:02:59.252751,Amazing collection of 9666 unique NFT dinosaur...,cover,approved,Byteosaurus,1,1,0,1,0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,-1.000000,0,0.0000,0.171000,-0.250000,9,0.019000,0.684000,2.600000,36,0.019000,0.914000,47.0,5555,5555,40,0.019447,105.545000,0.0190,crypto-totem-nft,"2022-03-06, 09:45:20",2021-12-27T09:38:31.663638,Crypto totem is a collection of 5555 totems cr...,cover,approved,Crypto-Totem,0,0,0,1,0,http://cryptototem.fashionartworld.com/
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.042,-0.250000,3,0.0140,0.251500,-0.405437,18,0.013972,2.459500,0.045310,179,0.013740,85.369259,1578.0,9998,9998,916,0.054100,139.694278,0.0140,ultrapunks,"2022-03-06, 09:45:21",2021-03-09T19:01:30.147241,Ultra punks are punks inspired by official cry...,cover,approved,UltraPunks,1,1,0,1,1,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.035,0.166667,2,0.0175,0.261700,-0.728245,11,0.023791,2.961600,-0.002895,148,0.020011,79.350256,2280.0,4997,4997,1447,0.034803,118.883173,0.0200,etherbears,"2022-03-06, 09:45:21",2021-03-19T14:56:09.976599,"A happily grizzly bear named Ether , has his w...",cover,approved,EtherBears,0,1,1,1,0,http://etherbears.club/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.090,0.000000,1,0.0900,0.180000,-0.389831,2,0.090000,0.672000,-0.658512,7,0.096000,26.084460,267.0,1,1,216,0.097695,0.090000,0.1000,whale-watchers,"2022-03-06, 09:59:30",2021-09-16T04:12:53.747982,Whale Watchers is an NFT Whale Tracking tool. ...,cover,not_requested,Whale Watchers,0,1,0,1,0,NaN
1419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.600,1.409639,2,0.3000,18.995185,0.218577,60,0.316586,65.335585,2.371429,244,0.267769,605.305735,2255.0,2778,2778,448,0.268428,879.477065,0.0950,glewme-city-real-estate,"2022-03-06, 09:59:30",2021-01-31T22:34:37.460107,"Glewme City Real Estate, THE FIRST PHOTOREALI...",contain,requested,GLEWME CITY,0,1,0,0,0,http://Glewmecity.io
1420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.015,0.000000,1,0.0150,0.015000,0.000000,1,0.015000,0.015000,-0.347826,1,0.015000,0.528200,78.0,47,47,96,0.006772,0.705000,0.0050,yayo-catdog,"2022-03-06, 09:59:31",2021-04-03T14:30:56.865877,YAYO: CATDOG collection presents YAYO's new se...,contain,not_requested,YAYO: CATDOG,0,1,1,0,0,https://www.youtube.com/yayodrawing
1422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.050,0.000000,1,0.0500,0.100000,0.000000,2,0.050000,0.100000,0.000000,2,0.050000,0.100000,2.0,4,4,3,0.050000,0.200000,0.0500,crypto-lighthouses-3d,"2022-03-06, 09:59:32",2022-02-04T09:39:49.529378,Crypto Lighthouses 3D\n\nYou can use our Crypt...,padded,not_requested,Crypto Lighthouses 3D,1,0,1,1,0,NaN
1426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,-1.000000,0,0.0000,0.010000,0.000000,1,0.010000,0.010000,0.000000,1,0.010000,0.010000,1.0,321,321,3,0.010000,3.210000,0.0100,c321football,"2022-03-06, 10:02:08",2021-10-02T18:34:28.817760,"321 Football legends is a pixel-collection, co...",contain,not_requested,321 Football Legends,0,0,1,1,0,NaN

In [10]:
import sweetviz as sv

my_report = sv.analyze(col_df)
my_report.show_html() # Default arguments will generate to "SWEETVIZ_REPORT.html"

                                             |          | [  0%]   00:00 -> (? left)

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [11]:
col_df['stats_total_volume']

0         11.497400
1        205.010570
2          0.914000
3         85.369259
4        736.411086
           ...
1422       0.100000
1423    3231.763535
1424    5450.229352
1425     223.571313
1426       0.010000
Name: stats_total_volume, Length: 1427, dtype: float64

In [12]:
sourceFile = open('value_counts_collections.txt', 'w',encoding='utf-8')
for col in col_df.columns:
  
   print('$$$$$$$$$$$$$$$$$$$$$$$$$$$##############%%%%%%%%%%%%% \n',col_df[col].value_counts(dropna=False),'\n',file = sourceFile)
    
sourceFile.close()

In [15]:
col_df[['slug','name','primary_asset_contracts_name']]

,slug,name,primary_asset_contracts_name
0,spiritman,Spirit Man,NaN
1,byteosaurus,Byteosaurus,NaN
2,crypto-totem-nft,Crypto-Totem,NaN
3,ultrapunks,UltraPunks,NaN
4,whaletogether,WhaleTogether,AlphieWhales
...,...,...,...
1422,crypto-lighthouses-3d,Crypto Lighthouses 3D,NaN
1423,huxley-comics,HUXLEY Comics,HUXLEY Comics
1424,superfarm,SuperFarm Genesis Series,Unidentified contract
1425,squishy-apes-nft,Squishy Apes by Degen Labs,Squishy Apes
1426,c321football,321 Football Legends,NaN

In [ ]:
#slug,name similiar